### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by dylanjha** [manatlan/reqman#1]
> Now, you can edit your rml file, and try the things available in this tuto. 

The link "tuto" in the README is broken, not sure which example you're trying to link to

**Comment by manatlan** [comment]
thanks, fixed !

It's not really a tuto ( https://github.com/manatlan/reqman/blob/reqman1.4.4.0/examples/tuto.yml ).
It's a quick way to see the yaml syntax ... the big image.
